package com.mgmtp.gives.enums;

public enum CampaignTaskActivityAction {
    TASK_CREATED,
    STATUS_CHANGED,
    TITLE_UPDATED,
    DESCRIPTION_UPDATED,
    DUE_DATE_UPDATED,
    ASSIGNEE_ADDED,
    ASSIGNEE_REMOVED,
    LABEL_ADDED,
    LABEL_REMOVED,
    ATTACHMENT_ADDED,
    ATTACHMENT_REMOVED,
    TASK_ARCHIVED,
    TASK_UNARCHIVED,
    TASK_DELETED,
    TASK_RESTORED
}
