package com.mgmtp.gives.enums;

public enum NotificationType {
    DONATION_CONFIRMED,
    CAMPAIGN_DONATION_CONFIRMED,
    CAMPAIGN_STATUS_CHANGED,
    DONATION,
    CAMPAIGN_RESULT_POSTED,
    CAMPAIGN_ANNOUNCEMENT,
    ANNOUNCEMENT_REPLY,
    TASK_ASSIGNED,
    CAMPAIGN_UNJOIN_REQUESTED,
    CAMPAIGN_UNJOIN_APPROVED,
    CAMPAIGN_UNJOIN_REJECTED
}
