spring:
  application:
    name: mgm-gives

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mgmgives}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: ${MAIL_HOST:smtp-relay.brevo.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:9a4f2c8d3e7b1a5f6c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  mail:
    from-mail: ${FROM_MAIL:mgm.gives@vtk.io.vn}
    frontend-url: ${FRONTEND_URL:http://localhost:3000}
    verify-expiration: ${MAIL_VERIFY_EXPIRATION:864000000}
    reset-expiration: ${MAIL_RESET_EXPIRATION:864000000}
  media:
    upload-dir: ${APP_MEDIA_UPLOAD_DIR:/app/media}
  seed:
    admin:
      email: ${SEED_ADMIN_EMAIL}
      password: ${SEED_ADMIN_PASSWORD}
      full-name: ${SEED_ADMIN_FULL_NAME:Admin}
server:
  port: ${SERVER_PORT:8080}

logging:
  file:
    path: ${LOGGING_FILE_PATH:/app/logs}

payos:
  client-id: ${PAYOS_CLIENT_ID:2c4a32f6-9017-4913-b83c-a9735c36f34f}
  api-key: ${PAYOS_API_KEY:e99d3902-a69f-4eb4-b797-4bed2f35d087}
  checksum-key: ${PAYOS_CHECKSUM_KEY:3b10ff6db56cc7ebeda9cba74b20418387165ba7c3a1a6879763d60fa722757e}
  cancel-url: ${PAYOS_CANCEL_URL:http://mgm-gives.mgm-edv.de:3000}
  return-url: ${PAYOS_RETURN_URL:http://mgm-gives.mgm-edv.de:3000}
  webhook-url: ${PAYOS_WEBHOOK_URL:http://mgm-gives.mgm-edv.de:8082/api/donations/payos/webhook}
