-- Denormalized counters to avoid per-row COUNT/GROUP BY aggregation on feed reads.
-- Kept in sync via atomic increment/decrement at write time.
-- Corrected for drift by a periodic reconciliation job (see AnnouncementCounterReconciliationJob).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name='announcements' AND column_name='likes_count'
    ) THEN
        ALTER TABLE announcements ADD COLUMN likes_count INT NOT NULL DEFAULT 0;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name='announcements' AND column_name='replies_count'
    ) THEN
        ALTER TABLE announcements ADD COLUMN replies_count INT NOT NULL DEFAULT 0;
    END IF;
END $$;

-- Table for Likes
CREATE TABLE IF NOT EXISTS announcement_likes (
    announcement_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    
    PRIMARY KEY (announcement_id, user_id),
    CONSTRAINT fk_like_announcement FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_announcement_likes_user ON announcement_likes(user_id);

-- Table for Replies
CREATE TABLE IF NOT EXISTS announcement_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_edited BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Soft-delete audit columns
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by BIGINT REFERENCES users(id),
    deleted_by_role VARCHAR(20), -- 'AUTHOR', 'CAMPAIGN_CREATOR', 'ADMIN'
    
    CONSTRAINT fk_reply_announcement FOREIGN KEY (announcement_id) REFERENCES announcements(id) ON DELETE CASCADE,
    CONSTRAINT fk_reply_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Partial Index for active replies (smaller, faster, and excludes soft-deleted replies entirely)
CREATE INDEX IF NOT EXISTS idx_announcement_replies_active ON announcement_replies(announcement_id, id)
WHERE deleted_at IS NULL;

-- Announcement replies indexes (added to optimize performance)
-- 1. Index on announcement_id in announcement_replies
-- Why: The existing index (idx_announcement_replies_active) is a partial index (WHERE deleted_at IS NULL).
-- When an announcement is deleted, PostgreSQL needs to validate the foreign key constraint (fk_reply_announcement ON DELETE CASCADE)
-- across the ENTIRE table (including soft-deleted rows where deleted_at IS NOT NULL).
-- Without a full index, deleting an announcement will trigger a slow sequential scan on the replies table.
CREATE INDEX IF NOT EXISTS idx_announcement_replies_announcement_id ON announcement_replies(announcement_id);

-- 2. Index on user_id in announcement_replies
-- Why: Speeds up foreign key checks when a user is deleted or updated (fk_reply_user ON DELETE CASCADE).
-- It also optimizes user-centric queries (e.g., retrieving all replies posted by a specific user).
CREATE INDEX IF NOT EXISTS idx_announcement_replies_user_id ON announcement_replies(user_id);

-- 3. Index on deleted_by in announcement_replies
-- Why: Speeds up foreign key validation checks when a user is deleted or updated (fk_replies_deleted_by).
-- It is set as a partial index to save disk space and cache memory since the majority of replies are active (not deleted).
CREATE INDEX IF NOT EXISTS idx_announcement_replies_deleted_by ON announcement_replies(deleted_by) WHERE deleted_by IS NOT NULL;
